// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/form-data/form-data.d.ts
declare module "form-data" {
	export class FormData {
		append(key: string, value: any, options?: any): FormData;
		getHeaders(): Object;
		// TODO expand pipe
		pipe(to: any): any;
		submit(params: string|Object, callback: (error: any, response: any) => void): any;
	}
}
