# Nappikauppa2 CircleCI configuration file
#
# Builds nappikauppa2 docker image and publishes it to container registry

# Use newer version 2.1 which supports executors
version: 2.1
executors:
  # Custom docker in docker executor
  docker-runner:
    environment:
      # Docker image name
      IMAGE_NAME: teekkarispeksi/nappikauppa2
    docker:
      # Use latest debian buildpack deps as CI runtime
      - image: circleci/buildpack-deps:buster
jobs:
  # Build job for creating production image using multistage docker file
  build:
    executor: docker-runner
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - ./image.tar
      - run:
          name: Load Docker image cache
          command: |
            set +o pipefail
            docker load -i ./image.tar | true
      - run:
          name: Build Nappikauppa2 Docker image
          command: |
            docker build --cache-from=$IMAGE_NAME -t $IMAGE_NAME:latest .
      - run:
          name: Save Docker image
          command: |
            docker save -o image.tar $IMAGE_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ./image.tar
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  # Publish job for pushing image to container registry
  publish:
    executor: docker-runner
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish docker image to container registry
          command: |
            echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USERNAME --password-stdin $REGISTRY_URL
            IMAGE_TAG=${CIRCLE_TAG}
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$IMAGE_TAG
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$IMAGE_TAG
workflows:
  version: 2
  build-n-publish:
    jobs:
      # Run build for every commit and tag
      - build:
          filters:
            tags:
              only: /.*/
      # All tags are published to container registry
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
