# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build
      - run: bash build_build.sh
      - run: git describe --tags > tag

      - persist_to_workspace:
          root: .
          paths:
            - build
            - tag

      # run tests!
      # - run: yarn test
  deploy:
      docker:
        - image: circleci/node:7.10

      working_directory: ~/repo

      steps:
        - attach_workspace:
            at: .
        - run: mkdir /artifacts
        - run: cd build && yarn install --production
        - run: cd build && tar -czf /artifacts/nappikauppa2-`cat ../tag`.tar.gz *
        - store_artifacts:
            path: /artifacts

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
#            branches:
#              ignore: /.*/
