// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/1da639a106527e0c4010b354a1efe52a3059a291/node-uuid/node-uuid-cjs.d.ts
declare module "node-uuid" {
    var uuid: __NodeUUID.UUID;
    export = uuid;
}
